[build]
  publish = "out"
  command = "npm run build && npm run export"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://paintbox-api.railway.app"

[[redirects]]
  from = "/api/*"
  to = "https://paintbox-api.railway.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://paintbox-api.railway.app"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://paintbox-api.railway.app"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"